package com.translator;

import java.awt.*;
import java.awt.event.ActionEvent;
import javax.swing.*;

public class Display extends JFrame {

    //to get the state of the frame ans save it
    //when clicking Save
    private Settings settings;

    public Display(Settings settings) {
        this.settings = settings;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mainPanel = new JPanel();
        SaveButton = new JButton();
        nameOfApp = new JLabel();
        translateToLabel = new JLabel();
        languages = new JComboBox<>();
        tip1 = new JLabel();
        tip2 = new JLabel();
        startup = new JCheckBox();

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Translator");
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setLocationRelativeTo(null);

        SaveButton.setText("Save");
        SaveButton.addActionListener((e) -> save(e));

        nameOfApp.setFont(new Font("Tahoma", Font.BOLD, 24)); // NOI18N
        nameOfApp.setText("Translator");

        translateToLabel.setText("translate to:");

        languages.setModel(new DefaultComboBoxModel<>(new String[] { "Arabic", "English" }));
        languages.setSelectedItem(settings.getTranslateTo());

        tip1.setText("Tip: to use the app just copy the content");

        tip2.setText("you want to translate and press Ctrl+Shift+T");

        startup.setText("run on startup");
        startup.setSelected(settings.isOpenOnStartup());
        startup.setToolTipText("not functional for now!");

        GroupLayout mainPanelLayout = new GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveButton)
                        .addContainerGap())
                .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(startup)
                                .addComponent(tip2)
                                .addComponent(tip1)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(translateToLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(languages, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
                                .addComponent(nameOfApp))
                        .addContainerGap(47, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(nameOfApp)
                        .addGap(26, 26, 26)
                        .addComponent(tip1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tip2)
                        .addGap(27, 27, 27)
                        .addGroup(mainPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(translateToLabel)
                                .addComponent(languages, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(startup)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(SaveButton)
                        .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    //Handlers...
    private void save(ActionEvent evt) {
        //TODO figure how to run on startup (3:)
        settings.setOpenOnStartup(startup.isSelected());
        settings.setTranslateTo((String)languages.getSelectedItem());
        settings.saveSettings();
    }

    // Variables declaration - do not modify
    private JButton SaveButton;
    private JComboBox<String> languages;
    private JPanel mainPanel;
    private JCheckBox startup;
    private JLabel nameOfApp;
    private JLabel tip1;
    private JLabel tip2;
    private JLabel translateToLabel;
    // End of variables declaration
}
